name: gesture_app
description: A new Flutter project for Gesture App.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  # State Management
  flutter_bloc: ^8.1.3
  equatable: ^2.0.5

  # Routing
  go_router: ^12.1.0

  # Local Database
  hive: ^2.2.3
  hive_flutter: ^1.1.0

  # Networking
  dio: ^5.4.0

  # UI / Utility
  google_fonts: ^6.1.0
  flutter_svg: ^2.0.9
  gap: ^3.0.1
  
  # Permissions
  permission_handler: ^11.1.0

  # System Actions
  url_launcher: ^6.2.4
  torch_light: ^1.1.0
  vibration: ^3.1.5
  external_app_launcher: ^4.0.3
  flutter_overlay_window: ^0.5.0
  installed_apps: ^2.1.0
  flutter_contacts: ^1.1.9+2
  shake: ^3.0.0
  flutter_local_notifications: ^19.5.0
  home_widget: ^0.6.0
  uuid: ^4.5.2
  smooth_page_indicator: ^2.0.1
  http: ^1.6.0
  flutter_secure_storage: ^10.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  build_runner: ^2.4.7
  hive_generator: ^2.0.1

flutter:
  uses-material-design: true
